cc_library(
    name = "zmq_networking",
    hdrs = ["zmq_publisher.h"],
    visibility = ["//visibility:public"],
    deps = [
        "@libzmq//:libzmq",
        "@flatbuffers//:flatbuffers",
    ],
)
