name: Build And Test

on: [push, pull_request]

jobs:
  build:
    runs-on: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      uses: bazelbuild/setup-bazelisk@v3

    - name: Mount bazel cache  # Optional
      uses: actions/cache@v4
      with:
        path: "~/.cache/bazel"
        key: bazel

    - name: Build Project
      run: bazel build //...

    - name: Run Tests
      run: bazel test //...
